-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('DBuff_pb')


DBUFF = protobuf.Descriptor();
DBUFF_SN_FIELD = protobuf.FieldDescriptor();
DBUFF_TIMELEFT_FIELD = protobuf.FieldDescriptor();

DBUFF_SN_FIELD.name = "sn"
DBUFF_SN_FIELD.full_name = ".DBuff.sn"
DBUFF_SN_FIELD.number = 1
DBUFF_SN_FIELD.index = 0
DBUFF_SN_FIELD.label = 1
DBUFF_SN_FIELD.has_default_value = false
DBUFF_SN_FIELD.default_value = 0
DBUFF_SN_FIELD.type = 5
DBUFF_SN_FIELD.cpp_type = 1

DBUFF_TIMELEFT_FIELD.name = "timeLeft"
DBUFF_TIMELEFT_FIELD.full_name = ".DBuff.timeLeft"
DBUFF_TIMELEFT_FIELD.number = 2
DBUFF_TIMELEFT_FIELD.index = 1
DBUFF_TIMELEFT_FIELD.label = 1
DBUFF_TIMELEFT_FIELD.has_default_value = false
DBUFF_TIMELEFT_FIELD.default_value = 0
DBUFF_TIMELEFT_FIELD.type = 5
DBUFF_TIMELEFT_FIELD.cpp_type = 1

DBUFF.name = "DBuff"
DBUFF.full_name = ".DBuff"
DBUFF.nested_types = {}
DBUFF.enum_types = {}
DBUFF.fields = {DBUFF_SN_FIELD, DBUFF_TIMELEFT_FIELD}
DBUFF.is_extendable = false
DBUFF.extensions = {}

DBuff = protobuf.Message(DBUFF)

