-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local DItemBlood_pb = require("DItemBlood_pb")
module('DItem_pb')


DITEM = protobuf.Descriptor();
DITEM_SN_FIELD = protobuf.FieldDescriptor();
DITEM_NUM_FIELD = protobuf.FieldDescriptor();
DITEM_BIND_FIELD = protobuf.FieldDescriptor();
DITEM_TYPE_FIELD = protobuf.FieldDescriptor();
DITEM_ITEMID_FIELD = protobuf.FieldDescriptor();
DITEM_POSITION_FIELD = protobuf.FieldDescriptor();
DITEM_RUBYSN_FIELD = protobuf.FieldDescriptor();
DITEM_STRTHPROPPLUS_FIELD = protobuf.FieldDescriptor();
DITEM_STRTHLEVEL_FIELD = protobuf.FieldDescriptor();
DITEM_STRTHPERFECTPCT_FIELD = protobuf.FieldDescriptor();
DITEM_REFINEPROPPLUS_FIELD = protobuf.FieldDescriptor();
DITEM_PARAM_FIELD = protobuf.FieldDescriptor();
DITEM_COMBAT_FIELD = protobuf.FieldDescriptor();
DITEM_ITEMBLOOD_FIELD = protobuf.FieldDescriptor();

DITEM_SN_FIELD.name = "sn"
DITEM_SN_FIELD.full_name = ".DItem.sn"
DITEM_SN_FIELD.number = 1
DITEM_SN_FIELD.index = 0
DITEM_SN_FIELD.label = 1
DITEM_SN_FIELD.has_default_value = false
DITEM_SN_FIELD.default_value = 0
DITEM_SN_FIELD.type = 5
DITEM_SN_FIELD.cpp_type = 1

DITEM_NUM_FIELD.name = "num"
DITEM_NUM_FIELD.full_name = ".DItem.num"
DITEM_NUM_FIELD.number = 2
DITEM_NUM_FIELD.index = 1
DITEM_NUM_FIELD.label = 1
DITEM_NUM_FIELD.has_default_value = false
DITEM_NUM_FIELD.default_value = 0
DITEM_NUM_FIELD.type = 5
DITEM_NUM_FIELD.cpp_type = 1

DITEM_BIND_FIELD.name = "bind"
DITEM_BIND_FIELD.full_name = ".DItem.bind"
DITEM_BIND_FIELD.number = 3
DITEM_BIND_FIELD.index = 2
DITEM_BIND_FIELD.label = 1
DITEM_BIND_FIELD.has_default_value = false
DITEM_BIND_FIELD.default_value = 0
DITEM_BIND_FIELD.type = 5
DITEM_BIND_FIELD.cpp_type = 1

DITEM_TYPE_FIELD.name = "type"
DITEM_TYPE_FIELD.full_name = ".DItem.type"
DITEM_TYPE_FIELD.number = 4
DITEM_TYPE_FIELD.index = 3
DITEM_TYPE_FIELD.label = 1
DITEM_TYPE_FIELD.has_default_value = false
DITEM_TYPE_FIELD.default_value = 0
DITEM_TYPE_FIELD.type = 5
DITEM_TYPE_FIELD.cpp_type = 1

DITEM_ITEMID_FIELD.name = "itemId"
DITEM_ITEMID_FIELD.full_name = ".DItem.itemId"
DITEM_ITEMID_FIELD.number = 5
DITEM_ITEMID_FIELD.index = 4
DITEM_ITEMID_FIELD.label = 1
DITEM_ITEMID_FIELD.has_default_value = false
DITEM_ITEMID_FIELD.default_value = 0
DITEM_ITEMID_FIELD.type = 3
DITEM_ITEMID_FIELD.cpp_type = 2

DITEM_POSITION_FIELD.name = "position"
DITEM_POSITION_FIELD.full_name = ".DItem.position"
DITEM_POSITION_FIELD.number = 6
DITEM_POSITION_FIELD.index = 5
DITEM_POSITION_FIELD.label = 1
DITEM_POSITION_FIELD.has_default_value = false
DITEM_POSITION_FIELD.default_value = 0
DITEM_POSITION_FIELD.type = 5
DITEM_POSITION_FIELD.cpp_type = 1

DITEM_RUBYSN_FIELD.name = "rubySn"
DITEM_RUBYSN_FIELD.full_name = ".DItem.rubySn"
DITEM_RUBYSN_FIELD.number = 7
DITEM_RUBYSN_FIELD.index = 6
DITEM_RUBYSN_FIELD.label = 3
DITEM_RUBYSN_FIELD.has_default_value = false
DITEM_RUBYSN_FIELD.default_value = {}
DITEM_RUBYSN_FIELD.type = 5
DITEM_RUBYSN_FIELD.cpp_type = 1

DITEM_STRTHPROPPLUS_FIELD.name = "strthPropPlus"
DITEM_STRTHPROPPLUS_FIELD.full_name = ".DItem.strthPropPlus"
DITEM_STRTHPROPPLUS_FIELD.number = 8
DITEM_STRTHPROPPLUS_FIELD.index = 7
DITEM_STRTHPROPPLUS_FIELD.label = 1
DITEM_STRTHPROPPLUS_FIELD.has_default_value = false
DITEM_STRTHPROPPLUS_FIELD.default_value = ""
DITEM_STRTHPROPPLUS_FIELD.type = 9
DITEM_STRTHPROPPLUS_FIELD.cpp_type = 9

DITEM_STRTHLEVEL_FIELD.name = "strthLevel"
DITEM_STRTHLEVEL_FIELD.full_name = ".DItem.strthLevel"
DITEM_STRTHLEVEL_FIELD.number = 9
DITEM_STRTHLEVEL_FIELD.index = 8
DITEM_STRTHLEVEL_FIELD.label = 1
DITEM_STRTHLEVEL_FIELD.has_default_value = false
DITEM_STRTHLEVEL_FIELD.default_value = 0
DITEM_STRTHLEVEL_FIELD.type = 5
DITEM_STRTHLEVEL_FIELD.cpp_type = 1

DITEM_STRTHPERFECTPCT_FIELD.name = "strthPerfectPct"
DITEM_STRTHPERFECTPCT_FIELD.full_name = ".DItem.strthPerfectPct"
DITEM_STRTHPERFECTPCT_FIELD.number = 10
DITEM_STRTHPERFECTPCT_FIELD.index = 9
DITEM_STRTHPERFECTPCT_FIELD.label = 1
DITEM_STRTHPERFECTPCT_FIELD.has_default_value = false
DITEM_STRTHPERFECTPCT_FIELD.default_value = 0
DITEM_STRTHPERFECTPCT_FIELD.type = 5
DITEM_STRTHPERFECTPCT_FIELD.cpp_type = 1

DITEM_REFINEPROPPLUS_FIELD.name = "refinePropPlus"
DITEM_REFINEPROPPLUS_FIELD.full_name = ".DItem.refinePropPlus"
DITEM_REFINEPROPPLUS_FIELD.number = 11
DITEM_REFINEPROPPLUS_FIELD.index = 10
DITEM_REFINEPROPPLUS_FIELD.label = 1
DITEM_REFINEPROPPLUS_FIELD.has_default_value = false
DITEM_REFINEPROPPLUS_FIELD.default_value = ""
DITEM_REFINEPROPPLUS_FIELD.type = 9
DITEM_REFINEPROPPLUS_FIELD.cpp_type = 9

DITEM_PARAM_FIELD.name = "param"
DITEM_PARAM_FIELD.full_name = ".DItem.param"
DITEM_PARAM_FIELD.number = 12
DITEM_PARAM_FIELD.index = 11
DITEM_PARAM_FIELD.label = 1
DITEM_PARAM_FIELD.has_default_value = false
DITEM_PARAM_FIELD.default_value = ""
DITEM_PARAM_FIELD.type = 9
DITEM_PARAM_FIELD.cpp_type = 9

DITEM_COMBAT_FIELD.name = "combat"
DITEM_COMBAT_FIELD.full_name = ".DItem.combat"
DITEM_COMBAT_FIELD.number = 13
DITEM_COMBAT_FIELD.index = 12
DITEM_COMBAT_FIELD.label = 1
DITEM_COMBAT_FIELD.has_default_value = false
DITEM_COMBAT_FIELD.default_value = 0
DITEM_COMBAT_FIELD.type = 5
DITEM_COMBAT_FIELD.cpp_type = 1

DITEM_ITEMBLOOD_FIELD.name = "itemBlood"
DITEM_ITEMBLOOD_FIELD.full_name = ".DItem.itemBlood"
DITEM_ITEMBLOOD_FIELD.number = 14
DITEM_ITEMBLOOD_FIELD.index = 13
DITEM_ITEMBLOOD_FIELD.label = 1
DITEM_ITEMBLOOD_FIELD.has_default_value = false
DITEM_ITEMBLOOD_FIELD.default_value = nil
DITEM_ITEMBLOOD_FIELD.message_type = DItemBlood_pb.DITEMBLOOD
DITEM_ITEMBLOOD_FIELD.type = 11
DITEM_ITEMBLOOD_FIELD.cpp_type = 10

DITEM.name = "DItem"
DITEM.full_name = ".DItem"
DITEM.nested_types = {}
DITEM.enum_types = {}
DITEM.fields = {DITEM_SN_FIELD, DITEM_NUM_FIELD, DITEM_BIND_FIELD, DITEM_TYPE_FIELD, DITEM_ITEMID_FIELD, DITEM_POSITION_FIELD, DITEM_RUBYSN_FIELD, DITEM_STRTHPROPPLUS_FIELD, DITEM_STRTHLEVEL_FIELD, DITEM_STRTHPERFECTPCT_FIELD, DITEM_REFINEPROPPLUS_FIELD, DITEM_PARAM_FIELD, DITEM_COMBAT_FIELD, DITEM_ITEMBLOOD_FIELD}
DITEM.is_extendable = false
DITEM.extensions = {}

DItem = protobuf.Message(DITEM)

