-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('DProp_pb')


DPROP = protobuf.Descriptor();
DPROP_STR_FIELD = protobuf.FieldDescriptor();
DPROP_DEX_FIELD = protobuf.FieldDescriptor();
DPROP_CON_FIELD = protobuf.FieldDescriptor();
DPROP_INTE_FIELD = protobuf.FieldDescriptor();
DPROP_ATK_FIELD = protobuf.FieldDescriptor();
DPROP_DEF_FIELD = protobuf.FieldDescriptor();
DPROP_HIT_FIELD = protobuf.FieldDescriptor();
DPROP_DODGE_FIELD = protobuf.FieldDescriptor();
DPROP_CRIT_FIELD = protobuf.FieldDescriptor();
DPROP_TOUGH_FIELD = protobuf.FieldDescriptor();
DPROP_SPEED_FIELD = protobuf.FieldDescriptor();
DPROP_RESDEFGOLD_FIELD = protobuf.FieldDescriptor();
DPROP_RESDEFPOISON_FIELD = protobuf.FieldDescriptor();
DPROP_RESDEFCURSE_FIELD = protobuf.FieldDescriptor();
DPROP_HPMAX_FIELD = protobuf.FieldDescriptor();
DPROP_MPMAX_FIELD = protobuf.FieldDescriptor();
DPROP_COMBAT_FIELD = protobuf.FieldDescriptor();

DPROP_STR_FIELD.name = "str"
DPROP_STR_FIELD.full_name = ".DProp.str"
DPROP_STR_FIELD.number = 1
DPROP_STR_FIELD.index = 0
DPROP_STR_FIELD.label = 1
DPROP_STR_FIELD.has_default_value = false
DPROP_STR_FIELD.default_value = 0
DPROP_STR_FIELD.type = 5
DPROP_STR_FIELD.cpp_type = 1

DPROP_DEX_FIELD.name = "dex"
DPROP_DEX_FIELD.full_name = ".DProp.dex"
DPROP_DEX_FIELD.number = 2
DPROP_DEX_FIELD.index = 1
DPROP_DEX_FIELD.label = 1
DPROP_DEX_FIELD.has_default_value = false
DPROP_DEX_FIELD.default_value = 0
DPROP_DEX_FIELD.type = 5
DPROP_DEX_FIELD.cpp_type = 1

DPROP_CON_FIELD.name = "con"
DPROP_CON_FIELD.full_name = ".DProp.con"
DPROP_CON_FIELD.number = 3
DPROP_CON_FIELD.index = 2
DPROP_CON_FIELD.label = 1
DPROP_CON_FIELD.has_default_value = false
DPROP_CON_FIELD.default_value = 0
DPROP_CON_FIELD.type = 5
DPROP_CON_FIELD.cpp_type = 1

DPROP_INTE_FIELD.name = "inte"
DPROP_INTE_FIELD.full_name = ".DProp.inte"
DPROP_INTE_FIELD.number = 4
DPROP_INTE_FIELD.index = 3
DPROP_INTE_FIELD.label = 1
DPROP_INTE_FIELD.has_default_value = false
DPROP_INTE_FIELD.default_value = 0
DPROP_INTE_FIELD.type = 5
DPROP_INTE_FIELD.cpp_type = 1

DPROP_ATK_FIELD.name = "atk"
DPROP_ATK_FIELD.full_name = ".DProp.atk"
DPROP_ATK_FIELD.number = 5
DPROP_ATK_FIELD.index = 4
DPROP_ATK_FIELD.label = 1
DPROP_ATK_FIELD.has_default_value = false
DPROP_ATK_FIELD.default_value = 0
DPROP_ATK_FIELD.type = 5
DPROP_ATK_FIELD.cpp_type = 1

DPROP_DEF_FIELD.name = "def"
DPROP_DEF_FIELD.full_name = ".DProp.def"
DPROP_DEF_FIELD.number = 6
DPROP_DEF_FIELD.index = 5
DPROP_DEF_FIELD.label = 1
DPROP_DEF_FIELD.has_default_value = false
DPROP_DEF_FIELD.default_value = 0
DPROP_DEF_FIELD.type = 5
DPROP_DEF_FIELD.cpp_type = 1

DPROP_HIT_FIELD.name = "hit"
DPROP_HIT_FIELD.full_name = ".DProp.hit"
DPROP_HIT_FIELD.number = 7
DPROP_HIT_FIELD.index = 6
DPROP_HIT_FIELD.label = 1
DPROP_HIT_FIELD.has_default_value = false
DPROP_HIT_FIELD.default_value = 0
DPROP_HIT_FIELD.type = 5
DPROP_HIT_FIELD.cpp_type = 1

DPROP_DODGE_FIELD.name = "dodge"
DPROP_DODGE_FIELD.full_name = ".DProp.dodge"
DPROP_DODGE_FIELD.number = 8
DPROP_DODGE_FIELD.index = 7
DPROP_DODGE_FIELD.label = 1
DPROP_DODGE_FIELD.has_default_value = false
DPROP_DODGE_FIELD.default_value = 0
DPROP_DODGE_FIELD.type = 5
DPROP_DODGE_FIELD.cpp_type = 1

DPROP_CRIT_FIELD.name = "crit"
DPROP_CRIT_FIELD.full_name = ".DProp.crit"
DPROP_CRIT_FIELD.number = 9
DPROP_CRIT_FIELD.index = 8
DPROP_CRIT_FIELD.label = 1
DPROP_CRIT_FIELD.has_default_value = false
DPROP_CRIT_FIELD.default_value = 0
DPROP_CRIT_FIELD.type = 5
DPROP_CRIT_FIELD.cpp_type = 1

DPROP_TOUGH_FIELD.name = "tough"
DPROP_TOUGH_FIELD.full_name = ".DProp.tough"
DPROP_TOUGH_FIELD.number = 10
DPROP_TOUGH_FIELD.index = 9
DPROP_TOUGH_FIELD.label = 1
DPROP_TOUGH_FIELD.has_default_value = false
DPROP_TOUGH_FIELD.default_value = 0
DPROP_TOUGH_FIELD.type = 5
DPROP_TOUGH_FIELD.cpp_type = 1

DPROP_SPEED_FIELD.name = "speed"
DPROP_SPEED_FIELD.full_name = ".DProp.speed"
DPROP_SPEED_FIELD.number = 11
DPROP_SPEED_FIELD.index = 10
DPROP_SPEED_FIELD.label = 1
DPROP_SPEED_FIELD.has_default_value = false
DPROP_SPEED_FIELD.default_value = 0.0
DPROP_SPEED_FIELD.type = 2
DPROP_SPEED_FIELD.cpp_type = 6

DPROP_RESDEFGOLD_FIELD.name = "resDefGold"
DPROP_RESDEFGOLD_FIELD.full_name = ".DProp.resDefGold"
DPROP_RESDEFGOLD_FIELD.number = 12
DPROP_RESDEFGOLD_FIELD.index = 11
DPROP_RESDEFGOLD_FIELD.label = 1
DPROP_RESDEFGOLD_FIELD.has_default_value = false
DPROP_RESDEFGOLD_FIELD.default_value = 0
DPROP_RESDEFGOLD_FIELD.type = 5
DPROP_RESDEFGOLD_FIELD.cpp_type = 1

DPROP_RESDEFPOISON_FIELD.name = "resDefPoison"
DPROP_RESDEFPOISON_FIELD.full_name = ".DProp.resDefPoison"
DPROP_RESDEFPOISON_FIELD.number = 13
DPROP_RESDEFPOISON_FIELD.index = 12
DPROP_RESDEFPOISON_FIELD.label = 1
DPROP_RESDEFPOISON_FIELD.has_default_value = false
DPROP_RESDEFPOISON_FIELD.default_value = 0
DPROP_RESDEFPOISON_FIELD.type = 5
DPROP_RESDEFPOISON_FIELD.cpp_type = 1

DPROP_RESDEFCURSE_FIELD.name = "resDefCurse"
DPROP_RESDEFCURSE_FIELD.full_name = ".DProp.resDefCurse"
DPROP_RESDEFCURSE_FIELD.number = 14
DPROP_RESDEFCURSE_FIELD.index = 13
DPROP_RESDEFCURSE_FIELD.label = 1
DPROP_RESDEFCURSE_FIELD.has_default_value = false
DPROP_RESDEFCURSE_FIELD.default_value = 0
DPROP_RESDEFCURSE_FIELD.type = 5
DPROP_RESDEFCURSE_FIELD.cpp_type = 1

DPROP_HPMAX_FIELD.name = "hpMax"
DPROP_HPMAX_FIELD.full_name = ".DProp.hpMax"
DPROP_HPMAX_FIELD.number = 15
DPROP_HPMAX_FIELD.index = 14
DPROP_HPMAX_FIELD.label = 1
DPROP_HPMAX_FIELD.has_default_value = false
DPROP_HPMAX_FIELD.default_value = 0
DPROP_HPMAX_FIELD.type = 5
DPROP_HPMAX_FIELD.cpp_type = 1

DPROP_MPMAX_FIELD.name = "mpMax"
DPROP_MPMAX_FIELD.full_name = ".DProp.mpMax"
DPROP_MPMAX_FIELD.number = 16
DPROP_MPMAX_FIELD.index = 15
DPROP_MPMAX_FIELD.label = 1
DPROP_MPMAX_FIELD.has_default_value = false
DPROP_MPMAX_FIELD.default_value = 0
DPROP_MPMAX_FIELD.type = 5
DPROP_MPMAX_FIELD.cpp_type = 1

DPROP_COMBAT_FIELD.name = "combat"
DPROP_COMBAT_FIELD.full_name = ".DProp.combat"
DPROP_COMBAT_FIELD.number = 17
DPROP_COMBAT_FIELD.index = 16
DPROP_COMBAT_FIELD.label = 1
DPROP_COMBAT_FIELD.has_default_value = false
DPROP_COMBAT_FIELD.default_value = 0
DPROP_COMBAT_FIELD.type = 5
DPROP_COMBAT_FIELD.cpp_type = 1

DPROP.name = "DProp"
DPROP.full_name = ".DProp"
DPROP.nested_types = {}
DPROP.enum_types = {}
DPROP.fields = {DPROP_STR_FIELD, DPROP_DEX_FIELD, DPROP_CON_FIELD, DPROP_INTE_FIELD, DPROP_ATK_FIELD, DPROP_DEF_FIELD, DPROP_HIT_FIELD, DPROP_DODGE_FIELD, DPROP_CRIT_FIELD, DPROP_TOUGH_FIELD, DPROP_SPEED_FIELD, DPROP_RESDEFGOLD_FIELD, DPROP_RESDEFPOISON_FIELD, DPROP_RESDEFCURSE_FIELD, DPROP_HPMAX_FIELD, DPROP_MPMAX_FIELD, DPROP_COMBAT_FIELD}
DPROP.is_extendable = false
DPROP.extensions = {}

DProp = protobuf.Message(DPROP)

