-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('DVector2_pb')


DVECTOR2 = protobuf.Descriptor();
DVECTOR2_X_FIELD = protobuf.FieldDescriptor();
DVECTOR2_Y_FIELD = protobuf.FieldDescriptor();

DVECTOR2_X_FIELD.name = "x"
DVECTOR2_X_FIELD.full_name = ".DVector2.x"
DVECTOR2_X_FIELD.number = 1
DVECTOR2_X_FIELD.index = 0
DVECTOR2_X_FIELD.label = 1
DVECTOR2_X_FIELD.has_default_value = false
DVECTOR2_X_FIELD.default_value = 0.0
DVECTOR2_X_FIELD.type = 2
DVECTOR2_X_FIELD.cpp_type = 6

DVECTOR2_Y_FIELD.name = "y"
DVECTOR2_Y_FIELD.full_name = ".DVector2.y"
DVECTOR2_Y_FIELD.number = 2
DVECTOR2_Y_FIELD.index = 1
DVECTOR2_Y_FIELD.label = 1
DVECTOR2_Y_FIELD.has_default_value = false
DVECTOR2_Y_FIELD.default_value = 0.0
DVECTOR2_Y_FIELD.type = 2
DVECTOR2_Y_FIELD.cpp_type = 6

DVECTOR2.name = "DVector2"
DVECTOR2.full_name = ".DVector2"
DVECTOR2.nested_types = {}
DVECTOR2.enum_types = {}
DVECTOR2.fields = {DVECTOR2_X_FIELD, DVECTOR2_Y_FIELD}
DVECTOR2.is_extendable = false
DVECTOR2.extensions = {}

DVector2 = protobuf.Message(DVECTOR2)

