-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('test2_pb')


TEST2 = protobuf.Descriptor();
TEST2_ID_FIELD = protobuf.FieldDescriptor();
TEST2_NAME_FIELD = protobuf.FieldDescriptor();

TEST2_ID_FIELD.name = "id"
TEST2_ID_FIELD.full_name = ".Test2.id"
TEST2_ID_FIELD.number = 1
TEST2_ID_FIELD.index = 0
TEST2_ID_FIELD.label = 1
TEST2_ID_FIELD.has_default_value = false
TEST2_ID_FIELD.default_value = 0
TEST2_ID_FIELD.type = 5
TEST2_ID_FIELD.cpp_type = 1

TEST2_NAME_FIELD.name = "name"
TEST2_NAME_FIELD.full_name = ".Test2.name"
TEST2_NAME_FIELD.number = 2
TEST2_NAME_FIELD.index = 1
TEST2_NAME_FIELD.label = 1
TEST2_NAME_FIELD.has_default_value = false
TEST2_NAME_FIELD.default_value = ""
TEST2_NAME_FIELD.type = 9
TEST2_NAME_FIELD.cpp_type = 9

TEST2.name = "Test2"
TEST2.full_name = ".Test2"
TEST2.nested_types = {}
TEST2.enum_types = {}
TEST2.fields = {TEST2_ID_FIELD, TEST2_NAME_FIELD}
TEST2.is_extendable = false
TEST2.extensions = {}

Test2 = protobuf.Message(TEST2)

