-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local test2_pb = require("test2_pb")
module('test1_pb')


TEST1 = protobuf.Descriptor();
TEST1_TEST2_FIELD = protobuf.FieldDescriptor();
TEST1_ID_FIELD = protobuf.FieldDescriptor();

TEST1_TEST2_FIELD.name = "test2"
TEST1_TEST2_FIELD.full_name = ".Test1.test2"
TEST1_TEST2_FIELD.number = 1
TEST1_TEST2_FIELD.index = 0
TEST1_TEST2_FIELD.label = 3
TEST1_TEST2_FIELD.has_default_value = false
TEST1_TEST2_FIELD.default_value = {}
TEST1_TEST2_FIELD.message_type = test2_pb.TEST2
TEST1_TEST2_FIELD.type = 11
TEST1_TEST2_FIELD.cpp_type = 10

TEST1_ID_FIELD.name = "id"
TEST1_ID_FIELD.full_name = ".Test1.id"
TEST1_ID_FIELD.number = 2
TEST1_ID_FIELD.index = 1
TEST1_ID_FIELD.label = 1
TEST1_ID_FIELD.has_default_value = false
TEST1_ID_FIELD.default_value = 0
TEST1_ID_FIELD.type = 5
TEST1_ID_FIELD.cpp_type = 1

TEST1.name = "Test1"
TEST1.full_name = ".Test1"
TEST1.nested_types = {}
TEST1.enum_types = {}
TEST1.fields = {TEST1_TEST2_FIELD, TEST1_ID_FIELD}
TEST1.is_extendable = false
TEST1.extensions = {}

Test1 = protobuf.Message(TEST1)

